"""Dispatch Protocol — Runbook compiler.

Generates ORCHESTRATOR.md from agent registry + task schemas + health contracts.
The runbook is COMPILED, not hand-written — it can never drift.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.models import (
    AgentRegistry,
    HealthContract,
    Task,
)


def compile_orchestrator(
    agents_path: Path,
    tasks_dir: Path,
    health_path: Path,
    project_name: str = "Project",
    project_path: str = "",
    env_notes: str = "",
    rules: list[str] | None = None,
    output: Path | None = None,
) -> str:
    """Compile ORCHESTRATOR.md from all schema files.

    Returns the markdown string. If output is set, also writes to file.
    """
    # Load everything
    registry = AgentRegistry.from_yaml(agents_path)

    # System tasks to exclude from runbook
    SYSTEM_PREFIXES = (
        "apt-", "sysstat", "motd", "dpkg", "logrotate", "systemd-tmp",
        "man-db", "e2scrub", "fstrim", "update-notif", "apport", "snapd", "ua-timer",
    )

    tasks: list[Task] = []
    if tasks_dir.is_dir():
        for tf in sorted(tasks_dir.glob("*.yaml")):
            try:
                t = Task.from_yaml(tf)
                # Skip system tasks
                if any(t.id.startswith(p) for p in SYSTEM_PREFIXES):
                    continue
                tasks.append(t)
            except Exception:
                pass

    health = HealthContract.from_yaml(health_path) if health_path.exists() else HealthContract()

    # Sort tasks by priority
    priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    tasks.sort(key=lambda t: priority_order.get(t.priority.value, 2))

    # Build the runbook
    lines: list[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines.append(f"# {project_name} — Orchestrator Instructions")
    lines.append("")
    lines.append(f"> Auto-generated by Dispatch Protocol on {now}")
    lines.append("> **Do not hand-edit.** Regenerate with `dispatch compile`.")
    lines.append("")

    # Project location
    lines.append("## Project Location")
    lines.append("")
    if project_path:
        lines.append(f"```")
        lines.append(project_path)
        lines.append(f"```")
    else:
        lines.append("_Not specified — set with `--project-path`_")
    lines.append("")

    # Environment
    lines.append("## Environment")
    lines.append("")
    if env_notes:
        lines.append(env_notes)
    else:
        lines.append("_Check `.env` in the project root for credentials and configuration._")
    lines.append("")

    # Agent registry summary
    lines.append("## Registered Agents")
    lines.append("")
    lines.append("| Agent | Type | Platform | Schedule | Capabilities |")
    lines.append("|-------|------|----------|----------|-------------|")
    for name, agent in registry.agents.items():
        caps = ", ".join(agent.capabilities[:3])
        if len(agent.capabilities) > 3:
            caps += f" (+{len(agent.capabilities) - 3})"
        lines.append(f"| {name} | {agent.type.value} | {agent.platform.value} | {agent.schedule} | {caps} |")
    lines.append("")

    # Responsibilities — the core of the runbook
    lines.append("## Responsibilities")
    lines.append("")

    for i, task in enumerate(tasks, 1):
        priority_badge = {
            "critical": "🔴 Critical",
            "high": "🟠 High",
            "medium": "🟡 Medium",
            "low": "⚪ Low",
        }.get(task.priority.value, "Medium")

        lines.append(f"### {i}. {task.name} (Priority: {priority_badge})")
        lines.append("")
        lines.append(f"**Owner:** `{task.owner}`")
        lines.append(f"**Schedule:** {task.schedule.type.value}", )
        if task.schedule.every:
            lines[-1] += f" — every {task.schedule.every}"
        if task.schedule.cron:
            lines[-1] += f" — `{task.schedule.cron}`"
        lines.append("")

        # Execute block — copy-paste commands
        lines.append("**Execute:**")
        lines.append("```bash")
        if task.execute.workdir != ".":
            lines.append(f"cd {task.execute.workdir}")
        if task.execute.pre_run:
            lines.append(task.execute.pre_run)
        lines.append(task.execute.command)
        lines.append("```")
        lines.append(f"**Timeout:** {task.execute.timeout}")
        if task.execute.isolation:
            lines.append("**Isolation:** Yes (run in isolated session)")
        lines.append("")

        # Success criteria
        if task.success.metric:
            lines.append(f"**Success metric:** `{task.success.metric}`")
            if task.success.report.template:
                lines.append(f"**Report on success:** ({task.success.report.channel}) {task.success.report.template}")
            lines.append("")

        # Failure handling
        if task.failure.threshold:
            lines.append(f"**Failure threshold:** {task.failure.threshold} consecutive failures")
            if task.failure.report.template:
                lines.append(f"**Report on failure:** ({task.failure.report.channel}) {task.failure.report.template}")
            if task.failure.escalate:
                lines.append(f"**Escalate to:** `{task.failure.escalate.to}`")
                if task.failure.escalate.context:
                    lines.append(f"**Escalation context:**")
                    lines.append(f"> {task.failure.escalate.context}")
            lines.append("")

        # Conflict history
        if task.conflicts:
            lines.append("**Conflict history:**")
            for c in task.conflicts:
                lines.append(f"- ~~{c.agent}~~ ({c.resolution}): {c.reason}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Health checks
    lines.append("## Health Checks")
    lines.append("")

    if health.agent_checks:
        lines.append("### Agent Checks")
        lines.append("")
        lines.append("```bash")
        for ac in health.agent_checks:
            lines.append(f"# {ac.agent}: expect {ac.expect}")
            lines.append(ac.check)
        lines.append("```")
        lines.append("")

    if health.task_checks:
        lines.append("### Task Checks")
        lines.append("")
        lines.append("| Task | Check | Warn | Critical |")
        lines.append("|------|-------|------|----------|")
        for tc in health.task_checks:
            warn = str(tc.warn_below) if tc.warn_below is not None else "—"
            crit = str(tc.critical_below) if tc.critical_below is not None else "—"
            check_short = tc.check[:60] + "…" if len(tc.check) > 60 else tc.check
            lines.append(f"| {tc.task} | `{check_short}` | < {warn} | < {crit} |")
        lines.append("")

    # Escalation chain
    lines.append("### Escalation Chain")
    lines.append("")
    lines.append("```")
    lines.append("Level 0: Task runs normally")
    lines.append("    ↓ failure")
    lines.append("Level 1: Retry with backoff (agent handles internally)")
    lines.append(f"    ↓ threshold exceeded")
    lines.append(f"Level 2: Alert → {health.escalation.warn}")
    lines.append(f"    ↓ critical")
    lines.append(f"Level 3: Escalate → {health.escalation.critical}")
    lines.append("    ↓ still failing")
    lines.append("Level 4: Alert human with full context")
    lines.append("```")
    lines.append("")

    # Important rules
    lines.append("## Important Rules")
    lines.append("")
    default_rules = [
        "Always run `git pull` before executing any script.",
        "One owner per task — never duplicate across platforms.",
        "Every session starts fresh — re-read this file before every action.",
        "Report after every task run — what succeeded, what failed, what needs attention.",
        "Do NOT modify production databases without explicit approval.",
        "Do NOT send emails to curators without checking the outreach log first.",
    ]
    for rule in (rules or default_rules):
        lines.append(f"- {rule}")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(f"*Compiled by Dispatch Protocol — {now}*")
    lines.append(f"*Source: agents.yaml + tasks/*.yaml + health.yaml*")
    lines.append(f"*Regenerate: `dispatch compile --output ORCHESTRATOR.md`*")

    content = "\n".join(lines)

    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)

    return content
